### ISSUE TITLE
 How to calculate the camera matrix (the ppx ppy and focal length of each image)?

### ISSUE THREAD

**Issue by yuanxy92** [whuwuteng/benchmark_ISPRS2021#1]
I would like to map the calculated depth to 3d point clouds.
However, I did not find how are the images cropped from the original images, so I can not know the real ppx and ppy
Could you help me?

**Comment by whuwuteng** [comment]
Hello, because the aerial image is very large, so we crop the large image into small images for deep learning. At the same time, we want the disparity range small, so the image is not cropped in grid. So I do not the information for each cropped image.
I hope this is clear for you, I am sorry.
