### ISSUE TITLE
deep pruner pretrained model availability

### ISSUE THREAD

**Issue by rogermm14** [whuwuteng/benchmark_ISPRS2021#2]
Hello, thank you for sharing this impressive benchmark. 
I just wanted to ask if your pretrained deep pruner model is available. The current google drive link points to finetune_HRSnet.tar.
Thank you !
Roger

**Comment by whuwuteng** [comment]
Hello, I am sorry for this mistake(actually I uploaded it a long time ago), I have already updated it. You can download the model here https://drive.google.com/file/d/1XbkAZWi4lnLX823FyiCoAJ5XnbatWASR/view?usp=sharing.

**Comment by rogermm14** [comment]
Thank you so much !!
Best,
Roger
