### ISSUE TITLE
 How can we test the quantitative performance of new models on the testing data?

### ISSUE THREAD

**Issue by wuzhongwulidong** [whuwuteng/benchmark_ISPRS2021#3]
Thanks for your awesome work! 
However, as you know, the ground truth for the testing data is not provided. So, how can we test the quantitative performance of new models on the testing data?

By the way, the link of "_AI4GEO project_" actually points to the home page of AI4GEO, and we can not find the right web page to test the quantitative performance of my models on the testing data. 

So, could you please help and tell us how to test the quantitative performance of new models on the testing data?
Looking forward to your reply. Thank you very much.

**Comment by whuwuteng** [comment]
Hello, thank you very much for your interest in our work. I was really too busy from June to now, I am very sorry for the later answer.
I have uploaded the Ground Truth (GT) for the testing data, you can download the GT from Googledrive and Baidu pan, check the readme, I have updated it.
For the evaluation part, I just compare the prediction result with the GT, and then you can statistic the n-pixel error like most papers do.
